# Generated by Django 4.1.2 on 2022-11-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='default.png', null=True, upload_to='profile_photos'),
        ),
    ]
